###

name: Get AWS oracle data 

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  schedule:
    - cron:  '10 * * * *'
permissions:
  contents: write
env:
  AWS_KEY: ${{ secrets.AWS_KEY }}
  AWS_SECRET: ${{ secrets.AWS_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#       with:
#          token: ${{ secrets.PAT }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pandas
        pip install boto3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Data Collector 
      run: |
        python aws.py
    - name: commit
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/y2knot/oracle-fe.git
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
